name: CI

on:
    pull_request:
        branches:
            - "main"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        strategy:
            matrix:
                php: [7.2]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Install project deps
              run: composer install --no-progress

            - name: Install tools
              run: composer bin tools install --no-progress

            - name: Check style
              run: vendor-bin/tools/vendor/bin/phpcs

            - name: Run PHPStan
              run: vendor-bin/tools/vendor/bin/phpstan analyse

    test:
        needs: lint
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install project deps
              run: composer install --no-progress

            - name: Install tools
              run: composer bin tools install --no-progress

            - name: Run tests
              run: vendor-bin/tools/vendor/bin/phpunit

    php8:
        needs: lint
        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 8.1, 8.2, 8.3, 8.4]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install project deps
              run: composer install --no-progress

            - name: Install tools
              run: composer bin tools install --no-progress

            - name: Run tests
              run: vendor-bin/tools/vendor/bin/phpunit
